# Generated by Django 2.1.5 on 2019-02-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_intro_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='general', max_length=200),
        ),
    ]
